import numpy as np
print('numpy: %s' % np.__version__)
import tables as tb
print('pytables: %s' % tb.__version__)
import matplotlib as mpl
print('matplotlib: %s' % mpl.__version__)
import nbconvert as nb
print('nbconvert: %s' % nb.__version__)
import ipykernel as ipk
print('ipykernel: %s' % ipk.__version__)
