import numpy as np
print('numpy: %s' % np.__vervion__)
import tables as tb
print('pytables: %s' % tb.__vervion__)
import matplotlib as mpl
print('matplotlib: %s' % mpl.__vervion__)
import nbconvert as nb
print('nbconvert: %s' % nb.__vervion__)
import ipykernel as ipk
print('ipykernel: %s' % ipk.__vervion__)
